
sudo: required
language: java

jdk:
  - openjdk8

script:
  - mvn package -DskipTests

before_deploy:
    - mkdir MiningBuild
    - find . -name '*.jar' -exec cp {} ./MiningBuild \;
    - cd /home/travis/build/rafaresearch/hector/MiningBuild
    - tar -zcvf result.tar.gz *
deploy:
  provider: releases
  api_key:
    secure: $GITHUB_TOKEN
  file: result.tar.gz
  name: fetchjar-213f7887ea70eabdf0705cf8454de29af89e8c38
  file_glob: true
  overwrite: true
  skip_cleanup: true
  on:
    all_branches: true 
            